name: Run Python Tests
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install Python 3
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install .

            - name: Run tests with pytest
              run: coverage run -m pytest --html=test-report.html

            - name: Run coverage
              run: |
                  coverage report
                  coverage html

            - name: Archive code coverage results
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: code-coverage-report
                  path: htmlcov/index.html

            - name: Archive test report
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: test-report
                  path: |
                      test-report.html
                      assets
